version: "3.9"
services:
  back:
    container_name: annuvac_back
    build: src/back
    restart: always
    ports:
      - "8531:8531"
    networks:
      - api
    deploy:
      mode: replicated
      placement:
        constraints:
          - node.role == worker
      replicas: 1

  front:
    container_name: annuvac_front
    build: src/front
    restart: always
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "8530:80"
    networks:
      - api

networks:
  api:
    driver: bridge